superlists/lists/urls.py
from django.contrib import admin
from django.urls import path
from lists import views

app_name = "lists"

urlpatterns = [
    path('<int:list_id>/', views.view_list, name="view_list"),
    path('new', views.new_list, name='new_list')
]

superlists/superlists/urls.py
from django.contrib import admin
from django.urls import path, include
from lists import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page, name='home'),
    path('lists/', include('lists.urls')),
    # path('lists/<int:list_id>/', views.view_list, name="view_list"),
    # path('lists/<int:list_id>/add_item', views.add_item, name="add_item"),
    # path('lists/new', views.new_list, name='new_list')
]

superlists/lists/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class List(models.Model):

    # metoda pozwala na wskazywanie określonej strony dla elementu
    # zwroci odpowiedni widok adres url dla obiektu modelu (z odpowidnim id)
    # wywolanie redirect na obiektie automatycznie wywoluje get_absolute_url
    def get_absolute_url(self):
        return reverse('lists:view_list', args=[self.id])

# class Item(models.Model):
#     text = models.TextField(default="")
#     list = models.ForeignKey(List, default=None)
#
#     class Meta:
#         unique_together = ('list', 'text') # zapewnienie unikalnosci elementu w liście

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

superlists/lists/forms.py
from django import forms
from lists.models import Item
from django.core.exceptions import ValidationError

#
# class ItemForm(forms.Form):
#     item_text = forms.CharField(
#         widget=forms.fields.TextInput(attrs={ # dodanie widgetu podpwiedzi do formularza, co sprowadza sie do dodatnia adtybutów do htmla
#             'placeholder': "Wpisz rzecz do zrobienia",
#             'class': "form-control input-lg"
#         })
#     )

EMPTY_LIST_ERROR = "Element listy nie może być pusty"
DUPLICATE_ITEM_ERROR = "Podany element już istnieje na liście."


class ItemForm(forms.models.ModelForm):
    class Meta:
        model=Item # model dla ktorego jest przeznaczony formularz
        fields = ('text',) # pole do użycia
        widgets = { #dodanie atrybutow do html
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Wpisz rzecz do zrobienia',
                'class': 'form-control input-lg',
                }),
        }
        error_messages= {
            'text': {'required': EMPTY_LIST_ERROR}
        }

    def save(self, for_list):
        # instance przedstawia modyfikowany lub tworzony obiekt bazy danych
        self.instance.list = for_list
        return super().save() # zapisuje dane z formularza do bazy danych




class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

superlists/lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item, List
from django.core.exceptions import ValidationError
from lists.forms import ItemForm, ExistingListItemForm
# Create your views here.


# def home_page(request):
#     if request.method == 'POST':
#         new_item_text = request.POST['item_text']
#         Item.objects.create(text=new_item_text)
#     else:
#         new_item_text=""

#     return render(request, 'home.html', {
#         'new_item_text': new_item_text,
#     }) #D jango automatycznie szuka katalogow templates szuka pliku html i tworzony jest http request

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})


# def new_list(request):
#     print(dir(request))
#     list_ = List.objects.create()
#     item = Item(text=request.POST['text'], list=list_)
#     try:
#         item.full_clean() # sprawdzenie poprawności stworzonego obiektu
#         item.save()
#     except ValidationError:
#         list_.delete()
#         error = "Element listy nie może być pusty"
#         return render(request, "home.html", {"error": error})
#     return redirect(list_) # automatycznie wola get_absolute_url


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

superlists/lists/templates/base.html
{% load static %}
<html>
<head>
    <title>Listy rzeczy do zrobienia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'base.css' %}" rel="stylesheet" media="screen">
</head>
<body>

    <div class="container">

        <div class="col-md-6 col-md-offset-6 jumbotron">
            <div class="text-center">
               <h1>{% block header_text %}{% endblock %}</h1>
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                    {{ form.text }} {# Wywolanie to powoduje wygenerowanie elementu HTML dla pola typu text #}
                    {% csrf_token %}
                    {% if form.errors %}
                        <div class="form-group has-error">
                            <span class="help-block">{{ form.text.errors }}</span>
                        </div>
                    {% endif %}
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

    </div>

</body>
</html>

superlists/lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %} Utwórz nową Listy rzeczy do zrobienia {% endblock %}

{% block form_action %} {% url "lists:new_list" %} {% endblock %}

superlists/lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %} Twoja Listy rzeczy do zrobienia {% endblock %}

{% block form_action %} {% url "lists:view_list" list.id %} {% endblock %}

{% block table %}
    <table class="table" id="id_list_table">
        {% for item in list.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}